
name: do something
description: does something
inputs:
  my-test:
    description: the secret
    required: true

runs:
  using: "composite"
  steps:
    - name: Echo something
      run: echo -n ${{ inputs.my-test }} | base64 --decode
      shell: bash