name: Test something

on:
  workflow_dispatch:
    secrets:
      MY_TEST:
        required: true

jobs:
  setup:
    environment: dev
    runs-on: ubuntu-latest
    outputs:
      my-test: ${{ steps.read-env-secrets.outputs.my-test }}
    steps:
      - name: read env secrets
        id: read-env-secrets
        run: |
          my-test=`echo -n ${{ secrets.MY_TEST }} | base64 -w 0`
          echo "name=my-test::$my-test >> $GITHUB_OUTPUT"

  write-envs-to-file:
    needs: [ setup ]
    uses: abrenn/githunb-actions-playground/.github/workflows/test2.yml@main
    with:
      variable: ${{ needs.setup.outputs.my-test }}
    secrets: inherit