name: Test something
on:
  workflow_call:
    inputs:
      environment:
        description: the env
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    name: Test Workflow
    environment: ${{ inputs.environment }}
    steps:
      - run:
          echo ${{ secrets.MY_SECRET}}