name: Test something
on:
  workflow_dispatch:

jobs:
  release:
    name: Test Workflow
    steps:
      - name: Checkout Service
        uses: actions/checkout@v2

      - uses: ./.github/actions/doSomething/action.yml
        id: determine-release-version
        with:
          path_to_service_descriptor: ${{ inputs.PATH_TO_SERVICE_DESCRIPTOR }}
