name: Test something
on:
  workflow_call:
    secrets:
      MY_SECRET:
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    name: Test Workflow
    steps:
      - run:
          echo ${{ secrets.MY_SECRET}}