name: Test something
on:
  workflow_call:
    inputs:
      variable:
        description: the env
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    name: Test Workflow
    steps:
      - run:
          echo ${{ inputs.variable }}