name: Test something
on:
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    name: Test Workflow
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3
        with:
          repository: abrenn/githunb-actions-playground
          ref: main

      - uses: ./.github/actions/doSomething

  releaseAgaian:
    runs-on: ubuntu-latest
    name: Test Workflow
    steps:
      - name: Checkout Service
        uses: actions/checkout@v2

      - uses: ./.github/actions/doSomething
