name: Test something
on:
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    name: Test Workflow
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3
        with:
          repository: abrenn/githunb-actions-playground
          ref: main
      - name: Try to fail
        run: exit 1
      - uses: ./.github/actions/doSomething
        if: failure()

  releaseAgaian:
    runs-on: ubuntu-latest
    name: Test Workflow
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3
        with:
          repository: abrenn/githunb-actions-playground
          ref: main


      - name: Try to fail
        run: exit 1
      - uses: ./.github/actions/doSomething
