name: Test something

on:
  workflow_dispatch:
    secrets:
      MY_TEST:
        required: true

jobs:
  setup:
    environment: dev
    runs-on: ubuntu-latest
    outputs:
      my-test: ${{ steps.read-env-secrets.outputs.my-test }}
    steps:
      - name: read env secrets
        id: read-env-secrets
        run: |
          MULTI_LINES_TEXT="this is line one \n
                            this is line two \n
                            this is line three \n"    

          echo "MULTI_LINES_TEXT_ENV_VAR<<EOF" >> $GITHUB_ENV
          # here we can place the command that will generate multi-line text
          echo $MULTI_LINES_TEXT >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

  write-envs-to-file:
    needs: [ setup ]
    uses: abrenn/githunb-actions-playground/.github/workflows/test2.yml@main
    with:
      variable: ${{ env.MULTI_LINES_TEXT_ENV_VAR }}
    secrets: inherit