name: Test something

on:
  workflow_dispatch:
    secrets:
      TEST:
        required: true

jobs:
  testing:
    uses: abrenn/githunb-actions-playground/.github/workflows/test2.yml@main
    environment: dev
    secrets: inherit