name: Test something
on:
  workflow_dispatch:
    inputs:
      message:
        required: true
        description: something


jobs:
  testing:
    uses: abrenn/githunb-actions-playground/.github/workflows/test2.yml@main
    secrets:
      MY_SECRET: ${{ inputs.message }}